### ISSUE TITLE
Francine images

### ISSUE THREAD

**Issue by Veena1** [quickforms/pregapp#4]
I am not able to scroll the images sideways on any mobile device.

**Comment by beneze** [comment]
Hi Veena,
Are you free for a phone call this afternoon. Let me know a good time to call?
Thanks, Ben Eze

**Comment by Veena1** [comment]
Hi Ben,

 I am free after 12. You can call after that.
My no is 613-818-8008

Thanks
Veena

**Comment by beneze** [comment]
The scrolling issue has been fixed for all francine pages. Please ensure that you refresh the page on your browser since the previous pages may still be in your local cache.
